### ISSUE TITLE
I get the error "uknown firmware" when trying to load the software through GUI Tool

### ISSUE THREAD

**Issue by Gand46** [floppes/RTD266xFlash#12]
Hi i have the KD0350AV02 model but it gives me a problem with the GUI tool = Checking "firmware... Error! Unknown firmware. 

i upload the firmware 
[KD0350AV02.zip](https://github.com/floppes/RTD266xFlash/files/7147049/KD0350AV02.zip)

**Comment by Gand46** [comment]
the difference between mine and this [Issue #7](https://github.com/floppes/RTD266xFlash/issues/7) are the brightness control

**Comment by floppes** [comment]
Thank you for the file. I have added the firmware and released a new version.

**Comment by Gand46** [comment]
Thank you; it worked to change the logo png, logo color, and background logo color, but not the blue background; in any case, it looks great
![20210911_105536](https://user-images.githubusercontent.com/90488276/132953885-43413aed-75f3-4008-8260-b819865eaa9d.jpg)

**Comment by floppes** [comment]
You're right, the offset for the background color was wrong. I've published a new release. Can you try again please?

**Comment by Gand46** [comment]
Finally, I can make it look perfect. Thank you.

![20210911_114210](https://user-images.githubusercontent.com/90488276/132955141-92de6248-55ee-4bf2-9b12-155b896a8d7d.jpg)


You did a great job.
