### ISSUE TITLE
EEPROM ZB25VQ40ATIG

### ISSUE THREAD

**Issue by coucouillu** [floppes/RTD266xFlash#22]
Hi Floppes, 
i do not know ho to contact you.
I have a PCB800099 V9 board with RTD2660 and ZB25VQ40ATIG EEPROM
https://datasheet.lcsc.com/lcsc/2003172038_Zbit-Semi-ZB25VQ40ATIG_C495748.pdf

I try to backup the firmware before loading other ones.
I successfully connect to the BOARD through ARDUINO UNO with your sketch and with "RTD266xFlash.exe"  :

```
Connecting...
Connection error: timeout, retrying... (1/5)
Connection error: checksum error, retrying... (2/5)
Connection successful!
Reading status info... done
Manufacturer ID: 0x5E (Unknown)
Device ID: 0x12 (Unknown)
JEDEC Manufacturer ID: 0x5E (Unknown)
JEDEC Memory Type: 0x60
JEDEC Capacity: 0x13 (Unknown)
Status: 0x181C
```

But I am blocked in the "Read EEPROM" section. Indeed, I do not know what are the parameter of memory to be sure to read all the eeprom through "start adress" and "lenth" values.
Can you help?
Thank a lot.
Brice

**Comment by floppes** [comment]
> i do not know ho to contact you.

My e-mail address is in the "About" dialog ;)

If you want to read the whole EEPROM, enter 0 for the start address and the size of the EEPROM in bytes for the length. The EEPROM is usually 512 KiB, therefore enter 524288 for the length (512 * 1024).

Check the option "Outout file" and select the file where you want to save the EEPROM contents. You can uncheck "Output to log".
