### ISSUE TITLE
rtd2660 800x480 unknown firmware

### ISSUE THREAD

**Issue by yakaracolombia** [floppes/RTD266xFlash#25]
hello, first of all, thank you for the effort and your amazing work
I can modify a kedei 3.5 rpi screen perfectly

but when I try to modify a cheap Aliexpress  rtd2660h board controller I can write full firmwares but I can't change the boot logo or the input pop up
direct arduino says: error! cannot identify chip

and with the "firmware image option" says: unknown firmware
here is my actual firmware
[firmware-ykr.BIN.zip](https://github.com/floppes/RTD266xFlash/files/15283297/firmware-ykr.BIN.zip)

thank you for your time

**Comment by floppes** [comment]
Thank you for the firmware. Unfortunately, I cannot find the call to `CShowNoSignal()`. This is required to add it to the list of known firmwares to modify.
