### ISSUE TITLE
composite input option in kedei 3.5"

### ISSUE THREAD

**Issue by yakaracolombia** [floppes/RTD266xFlash#26]
Thank you for everything you do and for the ease of being able to write and modify our RTD2660.

I've been exploring the various modifications that people can achieve for a short time, and a question arose that could be an addition to your software.

We know that the RTD266x has AV/VGA/HDMI inputs, but on each board, only some are enabled or only one input is enabled, as is the case with my screen, which is the same as the one in the picture in your readme, a Kedei 3.5" HDMI. My question is:

Could the function be added to your software or in some way independently enabled, for example, the composite AV input, understanding that we would have to solder an additional cable to use the input and assign a simple pull-down as a source change button in the case of having two video sources active? Or even better for some projects, in your program, being able to select between a single input, for example, HDMI/AV, so that a source button is not needed.

I hope I'm not being a bother with my question, but this would help several projects that only have composite video signal.

And again, THANK YOU

**Comment by floppes** [comment]
Sorry, but I don't think this is possible with the way my tool works.

The features you want to add are selected by compiler switches before the firmware is compiled. For example, there is a switch called `_HDMI_SUPPORT`. If it is enabled, code for HDMI support is compiled into the firmware. If it is not enabled, the code will not be included in the firmware.

My tool modifies only few bytes in the binary firmware. It doesn't add new code or removes code. For the features you want to add, we would have to add new code into the binary firmware. This is barely possible. It would require us to update all memory addresses in all memory instructions. We can't do this with a binary firmware.

A better approch for you would be to compile the firmware for your board yourself. You can find the firmware source code on the Internet. There is also a project to write a custom firmware [here](https://bitbuilt.net/forums/index.php?threads/worklog-documentation-rtd2662-custom-firmware.2841/). But I don't know if they are still actively working on it.
