### ISSUE TITLE
Flasher crashes on Windows 10

### ISSUE THREAD

**Issue by Deadking2010** [floppes/RTD266xFlash#30]
I find that sometimes when trying to connect to the device or trying to upload the firmware the program just closes.  I can get to about 20% at times and then the program just closes.

Is there a preferred settings for windows?

I have also tried to run the programmer under Wine in Linux and I get a checksum error when trying to read data.

Any help would be appreciated.

**Comment by floppes** [comment]
Are you using the GUI tool? If yes and you have Visual Studio installed (the community edition is sufficient), you can run it in debug mode and see if you get an exception.

There are no special settings required in Windows.

**Comment by Deadking2010** [comment]
Yes I was using the GUI tool but I do not have visual studio installed.  I will install it and see what happens then.  Thanks.

**Comment by Deadking2010** [comment]
I was able to install Visual Studio and run the program,  it worked flawlessly.  Only thing I can think is that I did not have .Net installed and I was prompted to by VS.  I was able to flash a new firmware for the board and can confirm the new screen works as it should.

Thanks
