### ISSUE TITLE
JEDEC ID: 0x856013 Cannot setup chip commands. The flash chip id is unknown.

### ISSUE THREAD

**Issue by korbav** [floppes/RTD266xFlash#4]
Hello, first of all, thanks for the awesome job, the following is not quite an issue but much more an information request.

I'm trying to get my 7 inches Kedei flashed (using the RPi method), this screen is also managed by a RTD2660 chip.
When I launch the python script it stops with the following error message : 

```
JEDEC ID: 0x856013
Cannot setup chip commands. The flash chip id is unknown.
```

The script might not be ready for this device but I'm wondering if by any way I could make it work with my device?

Below are some pictures of the board in the case it brings more information to your knowledge : 

![20201201_111050](https://user-images.githubusercontent.com/6184386/100727726-ed238000-33c6-11eb-8559-ccd5c8d5a4f2.jpg)
![20201201_111118](https://user-images.githubusercontent.com/6184386/100727815-04fb0400-33c7-11eb-8e26-5e8b48dd4ce9.jpg)
![20201201_111258](https://user-images.githubusercontent.com/6184386/100727886-1e03b500-33c7-11eb-993d-457c3b664f26.jpg)

**Comment by floppes** [comment]
Hi korbav,

I can't really identify the EEPROM chip on your photos. It should be the one below the small flat flex cable.
They come from different manufacturers, yours looks like STMicroelectronics. They all usually speak the same protocol. You can simply try additing the manufacturer ID 0x85 in `RTD266xPy/rtd266x/rtd266x.py` line 204 and see if it works.

**Comment by korbav** [comment]
Hi floppes, thanks for your answer.

I just gave a try with your instructions and it worked well, the firmware can be extracted.

I then tried to modify it using the exe and faced this error message : 

```
Error! Unknown firmware. You can send your firmware and the name of the display (printed on the cable on the back side) to the author (floppes@gmx.de), maybe it can be added to the known firmwares.
```

Here is the firmware that has been output : [firmware](https://bit.ly/3qlyOgs)

It would be awesome if you could take a look or if you could give me the instructions to add this firmware.
The model of the device is KD070V02, the brand name is KeDei, based on a RTD2660 chip.

**Comment by floppes** [comment]
So far I have only had 3.5" displays from KeDei with a resolution of 480x320. They came with lots of different panels and firmwares and I analyzed only those firmwares for my hardware.

I don't have your board, but your firmware looks very similar to the ones I know. You can add the following code to RTD266xFlash\RTD266xFlash\Firmware.cs to make it known to the tool:

```
new Firmware("7\" KeDei KD070V02 1024x600", 0x260D8, 1507, 0x12346, 0xD04F, 0x14733, 0x13A31, 0x15577, new[]
{
	new HashInfo(0, 0x80000, "6EEF496354199EA4147F6EF5589194D7FD547CC43BC33E3567A0D2411A84C5AC", new []
	{
		new HashSkip(0xD04F + 0x1D, 48),
		new HashSkip(0x12346, 16),
		new HashSkip(0x13A31, 48),
		new HashSkip(0x14733, 1),
		new HashSkip(0x15577, 1),
		new HashSkip(0x260D8, 1507)
	})
})
```

You can try to modify your firmware with this. But especially for the boot logo, it may not work properly because of the different screen resolution.

With the RTD266x there is no real risk to brick your display. Even if you flash an invalid firmware, you can always reflash another. Just make sure you have a copy of your original firmware ;)

**Comment by korbav** [comment]
Thanks for your assistance, it did work well! Even the logo worked well, probably a bit small but you had foreseen it would happen since the project stands initially for lower resolutions.
It might be interesting for other people to update the project to handle this firmware, if you wish I can create a PR.

**Comment by floppes** [comment]
That's great, thanks for the feedback 👍
I have added the firmware and EEPROM manufacturer ID and published a new version. No need for a PR anymore ;)

**Comment by korbav** [comment]
> 
> 
> That's great, thanks for the feedback 👍
> I have added the firmware and EEPROM manufacturer ID and published a new version. No need for a PR anymore ;)

Awesome, thanks!

**Comment by Shackmeister** [comment]
Hi @floppes 

With newest version (2.6.0.0) I'm also getting the same error in the gui "Initialization error: could not detect chip type, unknown JEDEC id 0x856013". Am I doing something wrong or is this perhaps a bug?

**Comment by Shackmeister** [comment]
Datasheet and image of the EEprom is attached below:
https://datasheet.lcsc.com/szlcsc/1810010235_PUYA-P25Q40H-SSH-IT_C194873.pdf
![20210104_141558](https://user-images.githubusercontent.com/5279723/103539186-e42b4000-4e97-11eb-9a45-bbc7cc4f071a.jpg)

**Comment by floppes** [comment]
Right, I forgot to add the full JEDEC id to the Arduino project. korbav used the Python script without the Arduino, that's why it worked for him.
Can you please update your Arduino sketch and try again?

**Comment by Shackmeister** [comment]
Thanks Floppes, I'll get it tested right away.

**Comment by SparkyNZ** [comment]
Does anyone know where I can find a schematic/gerber file for this KD070V02 board?? I have sent an email to KeDei but I don't like my chances of getting a response.

I tried modifying the HDMI connector and the traces have come off the board.. so what I want to do is redesign the layout of the board so it will fit inside my nav unit casing in my car.
