### ISSUE TITLE
I get the error "uknown firmware" when trying to load the software through python

### ISSUE THREAD

**Issue by hell-boy420** [floppes/RTD266xFlash#7]
help im not really sure what to do. Did i just happen to get a non-compatible board? </3

**Comment by floppes** [comment]
More info from your side would be helpful.

- Name of your board
- Picture of your board
- Upload of your firmware

**Comment by hell-boy420** [comment]
![16138087490295928793149118050851](https://user-images.githubusercontent.com/78244614/108588875-bb142100-7318-11eb-86eb-1f6a6752ca84.jpg)
Thank you so much for the response! The model is: KD0350AV02. Its listed on Amazon under the brand Osoyoo, "Osoyoo 3.5" HDMI LCD Touch..." By upload of firmware do you mean the out.bin file? Thank you for the help!

**Comment by floppes** [comment]
That's a new board variant I haven't seen before. What is the physical resolution of the panel?
Yes, please upload out.bin.

**Comment by hell-boy420** [comment]
Sorry for the late response, it was late and i went to bed. Amazon says the "physical resolution" is 800x480 and the "Original resolution for the LCD is 480x320." I'm not to adept with GitHub and I'm unsure how to attach the out.bin file. Should I upload it and then create a link, or is there an easier way?

**Comment by floppes** [comment]
You can zip it and attach it by dragging & dropping it onto the input form.
You could also upload it somewhere and post the link here.

**Comment by hell-boy420** [comment]
[out.zip](https://github.com/floppes/RTD266xFlash/files/6016126/out.zip)
Okay, again thank you for the help!

**Comment by floppes** [comment]
Thanks, the firmware looks very similar to the ones I already have. I've added it to the tool and released v2.7.0.0. You can give it a try and see if it works for you.
Always keep the original firmware in case something goes wrong ;)

**Comment by hell-boy420** [comment]
Thank you so much! It works flawlessly :)

**Comment by floppes** [comment]
Great :)

**Comment by Gand46** [comment]
Hi i have the same board but it gives me the same problem with the GUI tool =  Checking "firmware... Error! Unknown firmware. You can send your firmware and the name of the display 

[KD0350AV02.zip](https://github.com/floppes/RTD266xFlash/files/7147045/KD0350AV02.zip)
