### ISSUE TITLE
self.i2c = SMBus(interface) IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Electronlibre2012** [floppes/RTD266xFlash#9]
Hello,

sorry to disturb you but i try your tutorial with a RPI4 and i have this error : 
` python rtd266x_flash.py -r 524288 out.bin
Traceback (most recent call last):
  File "rtd266x_flash.py", line 41, in <module>
    rtd = RTD266x(args.interface, 0x4A)
  File "/home/pi/RTD266xFlash/RTD266xPy/rtd266x/rtd266x.py", line 24, in __init__
    self.i2c = SMBus(interface)
IOError: [Errno 2] No such file or directory
`

the first issue is i cant detect anything with `sudo i2cdetect -y 2` only `sudo i2cdetect -r -y 11
` and then i found the 4A I2s module.

so i found with googling : in /boot/config.txt look for the [pi4] section and set this value dtoverlay=vc4-kms-v3d,
delete the "f" of fkms, and then i was able to `sudo i2cdetect -r -y 11` and found the 4A I2s of the screen but the above error is when i try to read the flash memory with `python rtd266x_flash.py -r 524288 out.bin`.

i understand that i should modify the bus number, because you use the 2 in your Pi3 config, but its slightly different with a Pi4, which is the bus 11 or i2s-11...if i have well understanding...

Any idea please?

Thanks!

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

EDIT : GET IT WORKING ON RPI4 : 
for those who use a Rpi4, the way is different than on Pi3 : check at : "https://www.ddcutil.com/raspberry/"
so i have just modify the boot.txt with `dtoverlay=vc4-kms-v3d` and installed ddcutil and comment the `dtparam=i2c2_iknowwhatimdoing`not needed for Pi4, 

the read firmware command is : 
`python rtd266x_flash.py -i 11 -r 524288 out.bin` where 11 is the bus interface...that why the error is complaining about "interface" value that was not provided in the command line...lol...i have understand what i am doing...

and flash command is : 
`python rtd266x_flash.py -i 11 -d out.bin out_modified.bin`

it works! no more blue background awfull screen and no more pop up messages lol, thanks!

**Comment by floppes** [comment]
A quick Google search for `smbus No such file or directory pi 4` returns some useful hints like running `sudo raspi-config` and enabling I2C. Did you try this already?

**Comment by Electronlibre2012** [comment]
Thanks for your fast reply!

look at the EDIT of my post...find the docs ;)

thanks! and nice work!

**Comment by floppes** [comment]
Thanks for the solution!
